build_mode_str:
  - debug
  - debug-sanitizer
  - release
  - release-debug

upload_enabled:
  - true
  - false

network:
  - ucx
  - gex

gpu_enabled:
  - true
  - false

python:
  - 3.10
  - 3.11

numpy_version:
  # Not 2.1.0 which segfaults on asarray() sometimes, see
  # https://github.com/numpy/numpy/pull/27249
  - ">=1.22,!=2.1.0"

cmake_version:
  - ">=3.20.1,!=3.23.0"
