repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        - id: check-json # checks that all json files have proper syntax
        - id: check-toml # checks that all toml files have proper syntax
        - id: debug-statements # check for debug statements
          exclude: '^config/aedifix/main.py$' # intentional
        - id: end-of-file-fixer # check all files end in a newline
          # handled by clang-format
          exclude_types: [c, c++, cuda]
        - id: pretty-format-json
          args: ['--autofix', '--indent=4']
        - id: trailing-whitespace # remove trailing whitespace
          # part of the diff
          exclude: '^cmake/patches/span_proper_cmake_project.diff$'
          # handled by clang-format
          exclude_types: [c, c++, cuda]
    - repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
            - id: isort
    - repo: https://github.com/psf/black
      rev: 24.1.1
      hooks:
            - id: black
    - repo: https://github.com/PyCQA/flake8
      rev: 7.0.0
      hooks:
            - id: flake8
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: 'v17.0.6'
      hooks:
        - id: clang-format
          files: \.(cu|cuh|h|hpp|cc|inl)$
          types_or: []
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v1.8.0'
      hooks:
        - id: mypy
          pass_filenames: false
          args: ['legate', 'tests', 'config', 'test.py']
          additional_dependencies: [numpy,pytest,pytest_mock,types-psutil]
    - repo: https://github.com/MarcoGorelli/cython-lint
      rev: v0.16.0
      hooks:
      - id: cython-lint
      - id: double-quote-cython-strings
    - repo: https://github.com/netromdk/vermin
      rev: 'v1.6.0'
      hooks:
      - id: vermin
        args: ['--config-file', './setup.cfg']
    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: '3.0.0'
      hooks:
        - id: shellcheck
          args: ['--enable=all', '--color=always', '-x', '--severity=error']
    - repo: local
      hooks:
        -   id: legate-defined
            name: legate-defined
            description: 'Find uses of ifdef LEGATE_ that should be using LegateDefined()'
            entry: ./scripts/pre-commit/legate_defined.sh
            language: script
            'types_or': [c++, c, cuda]
            require_serial: false
            stages: [pre-commit]
            exclude: '^(src/core/legate_c\.h|src/legate_preamble\.h|src/core/experimental/stl/detail/config\.hpp|src/core/utilities/compiler\.h|src/legate_defines\.h)$'
        -   id: legate-assert
            name: legate-assert
            description: 'Find uses of assert() that should be using LegateAssert()'
            entry: ./scripts/pre-commit/legate_assert.py
            language: python
            'types_or': [c++, c, cuda]
            require_serial: false
            stages: [pre-commit]
            exclude: '^(src/core/utilities/assert\.h|src/core/utilities/abort.h)$'
        -   id: c-begone
            name: c-begone
            description: 'Convert C standard library functions and types to C++ equivalent'
            entry: ./scripts/pre-commit/c_begone.py
            language: python
            'types_or': [c++, c, cuda]
            require_serial: false
            stages: [pre-commit]
            exclude: '^(src/core/utilities/abort.h)$'
        -   id: cmake-format
            name: cmake-format
            entry: ./scripts/pre-commit/cmake-format.bash cmake-format
            language: python
            types: [cmake]
            # Note that pre-commit autoupdate does not update the versions
            # of dependencies, so we'll have to update this manually.
            additional_dependencies:
              - cmakelang==0.6.13
            verbose: true
            require_serial: true
        -   id: cmake-lint
            name: cmake-lint
            entry: ./scripts/pre-commit/cmake-format.bash cmake-lint
            language: python
            types: [cmake]
            # Note that pre-commit autoupdate does not update the versions
            # of dependencies, so we'll have to update this manually.
            additional_dependencies:
              - cmakelang==0.6.13
            verbose: true
            require_serial: true

ci:
    autoupdate_schedule: quarterly

default_language_version:
    python: python3
