name: Build conda Release package

concurrency:
  group: ci-release-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "cpp-branch-*"

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        ucx-enabled:
          - true
          - false
        platform:
          - linux
        target-device:
          - gpu
          - cpu
        cmake-preset:
          - release-gcc
          - debug-sanitizer-gcc
          - debug-gcc
        upload-enabled:
          - false
        exclude:
          - cmake-preset: debug-gcc
            ucx-enabled: true
          - cmake-preset: debug-sanitizer-gcc
            target-device: gpu
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      platform: ${{ matrix.platform }}
      target-device: ${{ matrix.target-device }}
      cmake-preset: ${{ matrix.cmake-preset }}
      ucx-enabled: ${{ matrix.ucx-enabled }}
      build-type: release
      upload-enabled: ${{ matrix.upload-enabled }}
    secrets: inherit
