---
name: Build conda Nightly release and legate profiler package

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # Nightly at 10:00 PM

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - linux-aarch64
        target-device:
          - gpu
          - cpu
        build-mode:
          - debug
          - debug-sanitizer
          - release
          - release-debug
        network:
          - ucx
          - gex
        upload-enabled:
          - true
          - false
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      platform: ${{ matrix.platform }}
      target-device: ${{ matrix.target-device }}
      build-mode: ${{ matrix.build-mode }}
      build-type: release
      upload-enabled: ${{ matrix.upload-enabled }}
      python-version: ${{ matrix.python-version }}
      network: ${{ matrix.network }}
      nightly: true
    secrets: inherit

  build-legate-profiler:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-64
          - linux-aarch64
        exclude:
          - platform: linux-aarch64
    uses:
      ./.github/workflows/gh-legate-profiler.yml
    with:
      platform: ${{ matrix.platform }}
    secrets: inherit
