name: Build and test CPU legate.core.internal on GH

concurrency:
  group: ci-cpu-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "cpp-branch-*"

jobs:
  build-cpu:
    strategy:
      fail-fast: false
      matrix:
        cmake-preset: [debug-gcc, debug-sanitizer-gcc]
    uses:
      ./.github/workflows/gh-build.yml
    with:
      build-target: cpu
      cmake-preset: ${{ matrix.cmake-preset }}
      # Ref: https://docs.rapids.ai/resources/github-actions/#cpu-labels for `linux-amd64-cpu4`
      runs-on: ${{ github.repository == 'nv-legate/legate.core.internal' && 'linux-amd64-cpu4' || 'ubuntu-latest' }}
      sha: ${{ github.sha }}

  test-cpu:
    needs:
      - build-cpu
    strategy:
      fail-fast: false
      matrix:
        cmake-preset: [debug-gcc, debug-sanitizer-gcc]
        include:
          - { name: Pytest Unit Tests, test-scope: unit }
          - { name: mypy, test-scope: mypy }
    name: ${{ matrix.name }}
    uses:
      ./.github/workflows/gh-test.yml
    with:
      build-target: cpu
      runs-on: ${{ github.repository == 'nv-legate/legate.core.internal' && 'linux-amd64-cpu4' || 'ubuntu-latest' }}
      sha: ${{ github.sha }}
      cmake-preset: ${{ matrix.cmake-preset }}
      test-scope: ${{ matrix.test-scope }}

  cleanup:
    needs:
      - build-cpu
      - test-cpu
    # This ensures the cleanup job runs even if previous jobs fail or the workflow is cancelled.
    if: always()
    uses:
      ./.github/workflows/gh-cleanup.yml
    with:
      build-target: cpu
      sha: ${{ github.sha }}
