name: Build documentation

concurrency:
  group: ${{ startsWith(github.ref_name, 'cpp-branch') && format('unique-{0}', github.run_id) || format('ci-build-docs-on-{0}-from-{1}', github.event_name, github.ref_name) }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "cpp-branch-*"
      - "main"

jobs:
  build-and-test:
    name: Build documentation (${{ matrix.platform }}, ${{ matrix.target-device }}, ${{ matrix.build-mode }}, ucx enabled)
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
        target-device:
          - gpu
        build-mode:
          - release
    uses:
      ./.github/workflows/gh-build-docs.yml
    with:
      platform: ${{ matrix.platform }}
      target-device: ${{ matrix.target-device }}
      build-mode: ${{ matrix.build-mode }}
    secrets: inherit
