---
name: Build and Test

concurrency:
  group: ${{ startsWith(github.ref_name, 'main') && format('unique-{0}', github.run_id) || format('ci-build-and-test-on-{0}-from-{1}', github.event_name, github.ref_name) }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "branch-*"
      - "main"

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - linux-aarch64
        target-device:
          - gpu
          - cpu
        build-mode:
          - debug
          - debug-sanitizer
          - release
          - release-debug
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      build-mode: ${{ matrix.build-mode }}
      build-type: release
      network: ucx
      nightly: false
      platform: ${{ matrix.platform }}
      python-version: "3.10"
      target-device: ${{ matrix.target-device }}
      upload-enabled: false
    secrets: inherit

  tests-pass:
    if: always()
    needs:
      - build-and-test
    runs-on: linux-amd64-cpu4
    steps:
      - name: Check job results
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
