name: Build and test GPU legate.core on GH

concurrency:
  group: ci-gpu-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Lint legate.core on GH"]
    types:
      - completed
  push:
    branches:
      - "pull-request/[0-9]+"
      - "*branch-*"

jobs:
  build-gpu:
    strategy:
      fail-fast: false
      matrix:
        cmake-preset: [debug-gcc, debug-sanitizer-gcc]
    #if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'nv-legate' }}
    if: ${{ github.repository_owner == 'nv-legate' }}
    uses:
      ./.github/workflows/gh-build.yml
    with:
      build-target: gpu
      cmake-preset: ${{ matrix.cmake-preset }}
      # Ref: https://docs.rapids.ai/resources/github-actions/#cpu-labels for `linux-amd64-cpu4`
      repos-name: ${{ github.event.repository.name }}
      runs-on: ${{ contains(github.repository, 'nv-legate/legate.core') && 'linux-amd64-cpu4' || 'ubuntu-latest' }}
      sha: ${{ github.sha }}

  test-gpu:
    needs:
      - build-gpu
    strategy:
      fail-fast: false
      matrix:
        cmake-preset: [debug-gcc, debug-sanitizer-gcc]
        runner: [linux-amd64-gpu-v100-latest-1, linux-amd64-2gpu ]
        test-config: [{ name: Pytest Unit Tests, test-scope: unit }]
    name: ${{ matrix.test-config.name }}
    if: ${{ github.repository_owner == 'nv-legate' }}
    uses:
      ./.github/workflows/gh-test.yml
    with:
      build-target: gpu
      repos-name: ${{ github.event.repository.name }}
      runs-on: ${{ matrix.runner }}
      sha: ${{ github.sha }}
      cmake-preset: ${{ matrix.cmake-preset }}
      test-scope: ${{ matrix.test-config.test-scope }}

  cleanup:
    needs:
      - build-gpu
      - test-gpu
    # This ensures the cleanup job runs even if previous jobs fail or the workflow is cancelled.
    if: always()
    uses:
      ./.github/workflows/gh-cleanup.yml
    with:
      build-target: gpu
      sha: ${{ github.sha }}
