name: Lint legate.core on GH

on:
  push:
    branches:
      - "pull-request/[0-9]+"
      - "*branch-*"

jobs:
  lint:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: true
    if: ${{ github.repository_owner == 'nv-legate' }}
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - name: List machine info
        run: |
          uname -a
          lsb_release -a

      - name: List python version
        run: python3 --version

      - name: Checkout ${{ github.event.repository.name }} (= this repo)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bootstrap pip
        run: |
          curl -O https://bootstrap.pypa.io/get-pip.py
          python3 get-pip.py

      - name: Install requisite python packages
        run: |
          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install -U numpy traitlets vermin
          python3 -m pip install mypy==$(awk '/repo:.*mypy/{getline; print $2}' ./.pre-commit-config.yaml | tr -d \'v)


      - name: Run vermin on the repository
        run: |
          # can remove --exclude-regex flag (and un-comment the corresponding
          # exclusion_regex configuration in setup.cfg) once
          # https://github.com/netromdk/vermin/issues/236 is resolved, so insert version
          # check here so that we don't forget!
          [ $(vermin --version) == '1.5.2' ]
          vermin --config-file=./setup.cfg --exclude-regex 'build/' .

      - name: Run MyPy on the repository
        run: python3 -m mypy ./legate

      - name: Install LLVM 17
        working-directory: ~
        run: |
          # check if we can't install via apt-get, in which case we can remove all the
          # lines below this
          set -e
          ret=$(sudo apt-get install -y clang-tidy-17 > /dev/null 2>&1; echo $?)
          if [[ $ret -eq 0 ]]; then
            echo 'Can install clang-tidy-17 with apt-get, no longer need to install it manually!';
            exit 1;
          fi
          set +e
          # can remove all this if we can install with apt-get
          mkdir -p llvm-17
          cd llvm-17
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 17 all

      - name: List clang-tidy version
        run: |
          clang-tidy-17 --version
          # run-clang-tidy has no --version, so just print its location and help to make
          # sure it's there
          which run-clang-tidy-17
          run-clang-tidy-17 --help

      - name: Install Legion pre-reqs
        run: |
          # libdwarf
          sudo apt-get install -y libdw-dev

      - name: Configure legate.core
        # CMake Error: CMake was unable to find a build program corresponding to "Ninja".
        # CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build
        # tool.
        run: |
          cmake \
            --preset debug-clang \
            -G "Unix Makefiles" \
            -DLEGATE_CORE_CLANG_TIDY=clang-tidy-17 \
            -DLEGATE_CORE_RUN_CLANG_TIDY=run-clang-tidy-17

      - name: Run clang-tidy
        run: cmake --build --preset debug-clang --target tidy
