---
name: Build conda Nightly release and legate profiler packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # Nightly at 10:00 PM

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux
          - linux-aarch64
        target-device:
          - gpu
          - cpu
        build-mode:
          - release
          - release-debug
        network:
          - ucx
          - gex
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
        upload-enabled:
          - true
          - false
    uses:
      ./.github/workflows/gh-build-and-test.yml
    with:
      platform: ${{ matrix.platform }}
      target-device: ${{ matrix.target-device }}
      build-mode: ${{ matrix.build-mode }}
      build-type: nightly
      upload-enabled: ${{ matrix.upload-enabled }}
      upload-action: ${{ (matrix.build-mode == 'release' && 'upload-package-Anaconda' || 'upload-package-None') }}
      python-version: ${{ matrix.python-version }}
      network: ${{ matrix.network }}
      refname: ${{ github.ref_name }}
      default-branch: ${{ github.event.repository.default_branch }}
    secrets: inherit

  build-legate-profiler:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux-64
          - linux-aarch64
    uses:
      ./.github/workflows/gh-legate-profiler.yml
    with:
      platform: ${{ matrix.platform }}
    secrets: inherit
