name: Test legate.core on GH

on:
  workflow_call:
    inputs:
      build-target:
        required: true
        type: string
      repos-name:
        required: true
        type: string
      runs-on:
        required: true
        type: string
      sha:
        required: true
        type: string
      test-scope:
        required: true
        type: string
      cmake-preset:
        required: true
        type: string
      ucx-config:
        required: true
        type: string
      ucx-string:
        required: true
        type: string  

env:
  LEGATE_CORE_CMAKE_PRESET: ${{ inputs.cmake-preset }}

jobs:
  test:
    if: github.repository_owner == 'nv-legate'
    name: test-${{ inputs.build-target }}-${{ inputs.cmake-preset }}${{ inputs.ucx-string }}-sub-workflow
    runs-on: ${{ inputs.runs-on }}
    container:
      options: -u root
      image: ghcr.io/nv-legate/${{ inputs.repos-name }}-${{ inputs.build-target }}-${{ inputs.cmake-preset }}${{ inputs.ucx-string }}:${{ inputs.sha }}
      env:
        PYTHONDONTWRITEBYTECODE: 1
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
        LEGATE_CORE_CMAKE_PRESET: ${{ inputs.cmake-preset }}

    steps:
      - if: inputs.build-target == 'gpu'
        name: Run nvidia-smi to make sure GPU is working
        run: nvidia-smi

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        id: download
        with:
          name: "${{ inputs.repos-name }}-${{inputs.build-target}}-${{ inputs.cmake-preset }}-${{ inputs.sha }}"
          path: /home/coder/artifacts

      - name: Display structure of downloaded artifacts
        run: |
          pwd
          ls -R
        working-directory: ${{ steps.download.outputs.download-path }}

      - name: Install legate core
        shell: su coder {0}
        run: |
          mamba uninstall -y -n "${DEFAULT_CONDA_ENV:-legate}" numpy
          mamba install -y -n "${DEFAULT_CONDA_ENV:-legate}" -c nvidia -c conda-forge -c /tmp/conda-build/legate_core legate-core

      - name: Activate conda env
        shell: su coder {0}
        run: |
          . /opt/conda/etc/profile.d/conda.sh
          . /opt/conda/etc/profile.d/mamba.sh

          conda activate ${DEFAULT_CONDA_ENV:-legate}

      - name: Show conda env
        shell: su coder {0}
        run: |
          conda info

      - name: Run legate.core test / analysis
        shell: su coder {0}
        run: run-test-or-analysis ${{ inputs.test-scope }}
